language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package' && ci/sbt-deploy.sh
  && ci/gh-pages.sh
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    - https://webhooks.gitter.im/e/a803046bf00a8b62a326
    on_success: always
    on_failure: always
    on_start: never
env:
  global:
  - secure: "XtN4Fb0DN8cTdsZVuQHIUZEM/H/AvSp9H2MxYYenfArkamKYPBrUbcDqjqcb/k6AH/sx0G6qbpaQACp4FCeNnEKEmKdfDCzGWxhwzzUpqrcVlXIkRRCnNHdwOkxNzq2MV2QqwMTQDWNGPKcgLFkIo1VPXDBZVLJgGeN8sBOTmBs="
  - secure: "telk7+jnSCxJkVVugTiYkbvPNabEjebmKtShWZmIuu6XwUQSXbaZeZQr3MnUWo7qbeHdcL/ggQyB1uGQlmzwIDptPLP/76RI2UzQKKLj05JvrPLdu1lAOOfv3baVgbRtSCp/fxRCC/XohMb9geWssW1CFxgWkt9ilOHNWx64j30="