language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package' && ci/sbt-deploy.sh
  && ci/gh-pages.sh
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    - https://webhooks.gitter.im/e/a803046bf00a8b62a326
    on_success: always
    on_failure: always
    on_start: never
env:
  global:
  - secure: "HGgtd/cqYl49tB2SC8lupk6ThXLZSNpA6tlUCkrhsmNBWBE+B6yxk1HLGVA5D0DTBj2NEAT/G+aScYujVKi7GrqEfe8H0R9HgGwyPxZ71qdAAlTkDDiMcVStl/kOqTv1AU569ckYs6aJk0a+OGz2hSreB8BGuwXEB5UydDptbXI="
  - secure: "dZSv1bYKhrLaJ1aE+phCsrnHZzXVBBxXYd2r7o94DWXhHX05D8xjtSUekdrrIT9ljcbIuvGyVm5FYKCh3Qv2v0NHWkntr+uVNnPGo4g0uKE2xTsZqOv6ddmtbWSNpmj2h9zF7VIwvFIbtH6DWs4WWOt9dx6Fk4tbmKD29B23BRE="