language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package' 
- ci/sbt-deploy-to.sh libs-releases-local
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    - https://webhooks.gitter.im/e/a803046bf00a8b62a326
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - secure: ZGE+ZT5K7ogTvvMzGR7wy1oJ1C0PiehHnC79oM+yKOU33xUSU+/+414LrExs0dhWVtXn0ZymmkMf3cFhXfRHJfR9CB97eETVvPlj3S0AeIEN2+kEfeN+I9kRDrd4chvpEnyd9cE51deIBTl+ghdYwAOzUvRzMXkIxETj5odZr6c=
  - secure: GdNU7RH19VjztAsfj6KrsPvIgOcLuu+/djXUjWvageahh/kOpclfaN+6OzV84D/OK7jhK2+kjEtMpQBJONkGbd/z2ANvb5rdLTzH0VX1rC3tmwpP9nM8Q73RFN9gVPlxCm/o02l57gV1fG+ZR0rCBNgMQcM7enOgJgxOfMJCAfw=
